name: Build Windows Executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install Qt dependencies
      run: |
        pip install PyQt6
        pip install PyQt6-Qt6
        pip install PyQt6-sip

    - name: Build executable
      run: |
        pyinstaller --name maidou-pdf --onefile --noconsole --hidden-import PyQt6.QtCore --hidden-import PyQt6.QtGui --hidden-import PyQt6.QtWidgets --add-data "pdf_to_images.py;." --add-data "gui.py;." --add-data "analyze_text_data.py;." --add-data "templates;templates" run_gui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: maidou-pdf-windows
        path: dist/maidou-pdf.exe
